Test Deploy

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,7 @@ stages:
   - resolve-template-list
   - cfn-lint
   - cfn-changeset
+  - cfn-deploy
 
 variables:
   AWS_DEFAULT_REGION: 'us-east-1'
@@ -62,7 +63,7 @@ cf-lint:
     reports:
       junit: "*.xml"
 
-cf-changeset:
+.cf-changeset:
   stage: cfn-changeset
   script:
     - |
@@ -84,7 +85,70 @@ cf-changeset:
             --template-body file://${cftemplate} 
             --parameters $cfparams
         fi
-      else
 
-
+cf-deploy:
+  stage: cfn-deploy
+  script:
+    - |
+      for i in $(printenv | sed 's;=.*;;' | grep 'CF_'); do cfparams="${cfparams} ParameterKey=${i#CF_},ParameterValue=${!i}"; done;
+      echo $cfparams
       
+      RESOLVED_TEMPLATE_LIST=$(cat cftemplates.lst)
+
+      OIFS=$IFS;
+      IFS="|";
+      cffiles=($RESOLVED_TEMPLATE_LIST)
+      IFS=$OIFS
+
+      for cftemplate in "${cffiles[@]}"
+      do
+        echo ${cftemplate} 
+        
+        if ! aws cloudformation describe-stacks --region ${AWS_DEFAULT_REGION} --stack-name ${cftemplate} ; then
+
+          echo -e "\nStack does not exist, creating ..."
+          aws cloudformation create-stack \
+            --region ${AWS_DEFAULT_REGION} \
+            --stack-name ${cftemplate} \
+            --parameters $cfparams
+
+          if [[ ! -z ${SERIALIZED_EXECUTION} ]]; then
+            echo "Waiting for stack to be created ..."
+            aws cloudformation wait stack-create-complete \
+              --region ${AWS_DEFAULT_REGION} \
+              --stack-name ${cftemplate} 
+          fi
+
+        else
+          echo -e "\nStack exists, attempting update ..."
+
+          set +e
+          update_output=$( aws cloudformation update-stack \
+            --region ${AWS_DEFAULT_REGION} \
+            --stack-name ${cftemplate} \
+            --parameters $cfparams  2>&1)
+          status=$?
+          set -e
+
+          echo "$update_output"
+
+          if [ $status -ne 0 ] ; then
+
+            # Don't fail for no-op update
+            if [[ $update_output == *"ValidationError"* && $update_output == *"No updates"* ]] ; then
+              echo -e "\nFinished create/update - no updates to be performed"
+              exit 0
+            else
+              exit $status
+            fi
+
+          fi
+
+          if [[ ! -z ${SERIALIZED_EXECUTION} ]]; then
+            echo "Waiting for stack update to complete ..."
+            aws cloudformation wait stack-update-complete \
+              --region ${AWS_DEFAULT_REGION} \
+              --stack-name ${cftemplate}
+          fi
+
+        fi     
